### ISSUE TITLE
Instruction to generate Higgs to long lived particles

### ISSUE THREAD

**Issue by caredg** [JonaJJSJ-crypto/Proyecto-de-Tesis#16]
I leave these instructions here so I do not forget. They are based on [this config file](https://github.com/cms-sw/cmssw/blob/CMSSW_5_3_X/Configuration/Generator/python/Pythia_H0_pyupda_7TeV_cfi.py).

These commands are directly from some email from Felipe, who worked on this before.  One has to check everything and make sure to change what is needed.

gen Level:   cmsDriver.py Pythia_H0_pyupda_7TeV_cfi.py --step=GEN,SIM --datatier GEN-SIM --conditions=START53_LV6A1::All --pileup_input file:minibias.root --beamspot Realistic7TeV2011CollisionV2 --pileup 2011_FinalDist_OOTPU --fileout=gen.root --eventcontent RAWSIM --python_filename sim_cfg.py --number=10 --mc --no_exec

hlt Level: cmsDriver step1 --filein file:gen.root --step=DIGI,L1,DIGI2RAW,HLT:2011 --datatier GEN-RAW --conditions=START53_LV6A1::All --fileout=hlt.root --eventcontent RAWSIM --python_filename hlt_cfg.py --number=10 --mc --no_exec

reco Level:   step2 --filein file:hlt.root --fileout file:reco.root --mc --eventcontent AODSIM,DQM --conditions START53_LV6::All --step RAW2DIGI,L1Reco,RECO,VALIDATION:validation_prod,DQM:DQMOfflinePOGMC --python_filename reco_cfg.py --no_exec -n 10 --datatier AODSIM, DQM

en cada uno hay que cambiar las lineas

from Configuration.AlCa.GlobalTag import GlobalTag
process.GlobalTag = GlobalTag(process.GlobalTag, 'START53_LV6A1::All', '')

por lo siguiente

process.GlobalTag.connect = cms.string('sqlite_file:/cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1.db')
process.GlobalTag.globaltag = 'START53_LV6A1::All'

si quieres editar las propiedades de las particulas tienes que incluir tu porpia particle decay table en (no es necesario para que corra)

PYUPDAParameters = cms.vstring("PYUPDAFILE = \'my_pyupda.in\'"),  

en este caso mi archivo se llama my_pyupda.in. Lo puedes copiar de aqui https://github.com/fnavarro94/Open_Data_Simulation

Por ultimo hacer los links

ln -s /cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1.db

ln -s /cvmfs/cms-opendata-conddb.cern.ch/START53_LV6A1

Y listo, solamente correr en orden sim_cfg.py > hlt_cfg.py > reco_cfg.py

se me olvido, cerca de la linea 67 (puede que no se cree exactamente ahi) hay que elegir el pileup. El que estoy usando es este 

process.mix.input.fileNames = cms.untracked.vstring(['root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2011/Summer11LegDR/MinBias_TuneZ2_7TeV-pythia6/GEN-SIM/START53_LV4-v1/10000/00064CCC-A218-E311-A2E9-D485646A4E1A.root'])

**Comment by JonaJJSJ-crypto** [comment]
There exist a minor problem when running the Gen-Sim step for this repository Something that has to deal with PYUPDA reading. I contacted with Felipe and it seems the instructions work fine for another set of config files (in this [)repository](https://github.com/fnavarro94/Displaced_Vertex_Analyzer/tree/master/CMSSW_5_3_32/src) similar but not equal. 

In my case since I don't have the adequate database and global tags downloaded, so I had omitted all the modifications related to this. 

Another diference is that genSImstep and HLT step are made in a single process in the [)hlt_config.py](https://github.com/fnavarro94/Displaced_Vertex_Analyzer/blob/master/CMSSW_5_3_32/src/hlt_cfg.py), you can check by yourself that the GenSim step is influded here. 

I conclusion to replicate this simulations you have run:
cmsRun hlt_cfg.py
cmsRun reco_cfg.py
