### ISSUE TITLE
Pass LHE LW events through the full CMS simulation chain

### ISSUE THREAD

**Issue by JonaJJSJ-crypto** [JonaJJSJ-crypto/Proyecto-de-Tesis#7]

**Comment by caredg** [comment]
It is always good to study the guide for generation of events located in [CERN-OpenDataPortal](https://opendata.cern.ch/docs/cms-guide-event-production)

The instructions temporarily (that guide needs to be changed because the instructions work but not for external users) in the [CMS Open Data Guide](https://cms-opendata-guide.web.cern.ch/analysis/datasim/eventgeneration/) work.  Running the instructions there, I was able to produce the py and root files [here](https://cernbox.cern.ch/index.php/s/Cnz21UfPA6qleiP).  The final reco files look ok.

[Here](http://uaf-10.t2.ucsd.edu/~phchang/analysis/generator/genproductions/python/SevenTeV/) there are several original config files from ancient (Run 1) times.  The general hadronizer with LHE files should be the starting point.

**Comment by caredg** [comment]
We need to test this using the open data container

**Comment by caredg** [comment]
I tested the full process in the open data container.  Since we will make this (or a similar exercise) a package example in the [EventProductionExamplesTool](https://github.com/cms-opendata-analyses/EventProductionExamplesTool), I have put together some [preliminary instructions](https://codimd.web.cern.ch/s/kJjzlfYPq) that work.

**Comment by JonaJJSJ-crypto** [comment]
[LWSM200wDecay.lhe.gz](https://github.com/JonaJJSJ-crypto/Proyecto-de-Tesis/files/6671678/LWSM200wDecay.lhe.gz)
As you asked this is a fully functional .lhe with corrected cross section, yet Im not able to generate a consistent number of events

**Comment by caredg** [comment]
Thanks @JonaJJSJ-crypto.  This is weird.  Can you give us the UFO that we could include in madgraph for testing?

**Comment by JonaJJSJ-crypto** [comment]
The UFO is in our onedrive as LWSM200vCC (vCC will stand for Corrected CrossSection) if implementation is correct ill be uploading the file for the rest of the masses

**Comment by JonaJJSJ-crypto** [comment]
> I tested the full process in the open data container. Since we will make this (or a similar exercise) a package example in the [EventProductionExamplesTool](https://github.com/cms-opendata-analyses/EventProductionExamplesTool), I have put together some [preliminary instructions](https://codimd.web.cern.ch/s/kJjzlfYPq) that work.

Im not able to read the instructions  in CodiMD. I think im not able because of me logging in as a guest
![CodiMD](https://user-images.githubusercontent.com/78813250/122489942-6753d480-cfa6-11eb-83b5-08d4fec0f988.png)
![SIgn-On](https://user-images.githubusercontent.com/78813250/122489943-67ec6b00-cfa6-11eb-99ef-7a78ab3758a1.png)

**Comment by caredg** [comment]
I add the instructions here, for completeness

# Temporary instructions for CMS Simulation chain from LHE files

We will produce these events in four steps.  First we perform the loading of the LHE file, then the simulation up to the *SIM* step, followed by another intermedite step
up to the HLT simulation, and then the reconstruction. 

To start, first create a [VM](http://opendata.cern.ch/record/252 "CMS Open Data Portal") from the CMS Open Data website or a Docker container.

Then follow these steps:

- Create a CMSSW environment: 

    ```
    cmsrel CMSSW_5_3_32
    ```

- Change to the CMSSW_5_3_32/src/ directory:

    ```
    cd CMSSW_5_3_32/src/
    ```

- Initialize the CMSSW environment:

  ```
  cmsenv
  ```   

- Next, get your preferred LHE file.  We will use an example file, which can be found at `data/VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4.lhe`.

- In order to respect the structure of `CMSSW` repositories (which are assumed by the *cmsDriver* command), we will need to create an "EDAnalyzer" auxiliary package.  Its only purpose will be to place a needed configuration file in the correct area.

  
  ```
  mkdir MyPackage
  cd MyPackage
  mkedanlzr MySim
  ```

##### Step -1: Loading of the LHE file

- Execute the *cmsDriver* command as:

```
cmsDriver.py steplhe --filein file:VBFHiggs0MToZZTo4L_M-125p6_7TeV-JHUGenV4.lhe --fileout file:LHE.root --mc --eventcontent LHE --datatier GEN --conditions START53_LV6A1::All --step NONE --python_filename LHE.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 10
```

This generates a `LHE.py` configuration file which can then be run with the CMSSW executable.

- Run the CMSSW executable in the background

```
cmsRun LHE.py > lhe.log 2>&1 &
``` 

- Optionally, check the development of the job. You can do this periodically and exit at any time with CTRL+C:

```
tail -f lhe.log
``` 

##### Step 0: Generation and simulation

Note that the file `Hadronizer_TuneZ2_7TeV_generic_LHE_pythia_tauola_cff.py`, which can be found in the `data` folder of this repository, should be copied to our new `MyPackage/MySim/python/` area.  Otherwise, the *cmsDriver* command will not be able to find it.

- Once you have done the above, compile:

  ```
  scram b
  ```

- Now execute the *cmsDriver* command as:

```
cmsDriver.py MyPackage/MySim/python/Hadronizer_TuneZ2_7TeV_generic_LHE_pythia_tauola_cff.py --filein file:LHE.root --fileout file:sim.root --mc --eventcontent RAWSIM --customise SimG4Core/Application/reproc2011_2012_cff.customiseG4,Configuration/DataProcessing/Utils.addMonitoring --datatier GEN-SIM --conditions START53_LV6A1::All --beamspot Realistic7TeV2011CollisionV2  --step GEN,SIM --datamix NODATAMIXER --python_filename sim.py --no_exec -n 10
```

More information about the *--datatier* used can be found in the [CMS Workbook](https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookDataFormats); that is the level of information we need/want in our ROOT output file.

Notice also that wee have used
the `START53_LV6A1::All` conditions, because this is the snapshot of the conditions database we need.  More information about this can
be found in the [CMS Guide for Conditions](http://opendata.cern.ch/docs/cms-guide-for-condition-database) documentation.  As noted above, for this first step, step 0, we
only do the *GEN* and *SIM* parts of the whole chain.  We only generate 10 events for this example and choose the name of *sim* for the output files
in order to identify them correctly.

After executing this command, we will get the *sim.py* configuration file, which will be run with the *cmsRun* executable.  

- Run the CMSSW executable in the background

```
cmsRun sim.py > sim.log 2>&1 &
``` 

- Optionally, check the development of the job. You can do this periodically and exit at any time with CTRL+C:

```
tailf sim.log
```


##### Step 1: HLT


- Execute the *cmsDriver* command as:

```
cmsDriver.py step1 --filein file:sim.root --fileout file:hlt.root --mc --eventcontent RAWSIM --runsScenarioForMC Run2012_AB_C_D_oneRunPerEra --datatier GEN-RAW --conditions START53_LV6A1::All --step DIGI,L1,DIGI2RAW,HLT:2011 --python_filename hlt.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 10 --pileup_input root://eospublic.cern.ch//eos/opendata/cms/MonteCarlo2011/Summer11LegDR/MinBias_TuneZ2_7TeV-pythia6/GEN-SIM/START53_LV4-v1/10000/00064CCC-A218-E311-A2E9-D485646A4E1A.root --pileup 2011_FinalDist_OOTPU
```

Note here that the ROOT file *sim.root*, which was obtained in the last step (step 0), serves as input for step1.  

The MinBias file with pile-up events used is a particular example made available for these instructions.  Be aware that these files may or may not be available as part of an official release, and that one may need to simulate those as well.

We now process the event up to the high level trigger (HLT) simulation.  This command produces a file, *hlt.py*.

- Now, run the CMSSW executable in the background

```
cmsRun hlt.py > hlt.log 2>&1 &
``` 


- Optionally, check the development of the job. You can do this periodically and exit at any time with CTRL+C:

```
tail -f hlt.log
```

##### step 2: RECO (AOD)

- Execute the *cmsDriver* command as:

```
cmsDriver.py step2 --filein file:hlt.root --fileout file:reco.root --mc --eventcontent AODSIM,DQM --datatier AODSIM,DQM --conditions START53_LV6A1::All --step RAW2DIGI,L1Reco,RECO,VALIDATION:validation_prod,DQM:DQMOfflinePOGMC --python_filename reco.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 10
```

Note here that the ROOT file *hlt.root*, which was obtained in the last step (step 1), serves as input for step2.  
We now process the event up to the final step: the reconstruction (RECO).  This command produces a file, *reco.py*.

- Now, run the CMSSW executable in the background

```
cmsRun reco.py > reco.log 2>&1 &
``` 

- Optionally, check the development of the job. You can do this periodically and exit at any time with CTRL+C:

```
tail -f reco.log
```

The resulting ROOT file, *reco.root*, is in the same format as 
the MC and Data released by CMS.
File 1 of 1
Get a public link | Download

**Comment by JonaJJSJ-crypto** [comment]
I have already passed 10 testing events throw the whole simulation. for Mlw=200Gev. In porpouse to test a proper displaced vector

**Comment by caredg** [comment]
Acerca de correr el phythia hadronizer con slha:

Encontré estos dos archivos, `myHadronizer_test7.py` y `simTemplate_ssusy.py` que se pueden entrar en [esta carpeta](https://cernbox.cern.ch/index.php/s/3YH4EZzuT1ejeX5).  Realmente el más actualizado es el primero.  Ahí se muestra un ejemplo (que funcionó bien) de cómo alimentar eventos LHE, pero leyendo los parámetros de un archivo slha (que están también en la carpeta arriba). Hay que alimentar los dos, el LHE y el correspondiente SLHA. Nota que el `myHadronizer_test7.py` se creo con un  una línea para el cmsDriver como se muestra en la cabecera:

`Configuration/Generator/myHadronizer.py --step GEN,SIM,DIGI,L1,DIGI2RAW,HLT:7E33v2,RAW2DIGI,L1Reco,RECO --conditions START53_V7A::All --pileup 2012_Summer_50ns_PoissonOOTPU --datamix NODATAMIXER --eventcontent AODSIM --datatier AODSIM --no_exec --filein /uscms_data/d2/ecarrera/stealth_susy/data_example/T2_1000_150/T2_1000_150.lhe --filetype LHE --fileout test.root`

Para probar, por ahora, puedes suprimir el --pileup (eso hay que investigar cómo hacer mirando las simulaciones del 2012 en el Cern Open Data Portal, e.g., [estos switches](https://opendata.cern.ch/eos/opendata/cms/configuration-files/MonteCarlo2012/59687d1d79393aecf64d6439b6bfa710.configFile.py)). Por ahor concentrémonos en mirar si se producen eventos correctamente, luego miramos el pile-up mixing. 

El archivo `myHadronizer.py` también está en la carpeta arriba y corresponde a la más simple configuración del Pythia8HadronizerFilter (que debe andar por algún lado en github).  Creo que es el mismo `Configuration/Generator/python/Hadronizer_MgmMatchTune4C_8TeV_madgraph_pythia8_cff.py` sin el jetmatching, que no necesitamos (en principio).  Acá está la [documentación](https://twiki.cern.ch/twiki/bin/view/CMS/Pythia8Interface).

Esto es para generar con 8TeV, es decir datasets del 2012.  Esto es a lo mejor buena idea, pues podemos utilizar solamente datasets del 2012 y no nos fijamos en lo demás.  En fin, en 2012 parece que ya se podía correr todo en un mismo paso (es decir no había de hacer tantos pasos para primero hacer el gen, luego sim, luego hlt y luego reco), esa es otra ventaja.  

@JonaJJSJ-crypto, déjame saber si tiene sentido.  Para probar por mi cuenta necesitaría un archivo lhe y un slha correspondiente.

**Comment by JonaJJSJ-crypto** [comment]
[unweighted_events.lhe.gz](https://github.com/JonaJJSJ-crypto/Proyecto-de-Tesis/files/6744821/unweighted_events.lhe.gz)
[param_card.txt](https://github.com/JonaJJSJ-crypto/Proyecto-de-Tesis/files/6744824/param_card.txt)

**Comment by caredg** [comment]
Este tema está cerrado, pero queda como referencia para la producción masiva en #24
